### ISSUE TITLE
Arduino dashboard does not display the chart

### ISSUE THREAD

**Issue by anbayanyay** [thorrak/fermentrack#292]
I was prompted today to update the Fermentrack install from Github, which I did. Now my dashboard chart for my Arduino Uno isn't appearing. Here is a screen shot.
![screenshot](https://user-images.githubusercontent.com/41460011/42982109-ef8c14b2-8b9c-11e8-9aa2-fc3d72f3cc36.png)
If it helps, my /var/log/nginx/error.log is filled with recent lines that are all pretty much this, with the socket number incrementing...

> 2018/07/19 07:51:51 [error] 626#626: *249164 upstream prematurely closed connection while reading upstream, client: ::ffff:192.168.1.107, server: _, request: "GET /devices/2/dashboard/beer/2/annotations.json HTTP/1.1", upstream: "http://127.0.0.1:8123/devices/2/dashboard/beer/2/annotations.json", host: "192.168.1.49", referrer: "http://192.168.1.49/devices/2/dashboard/"
Please let me know if any other information may help diagnose this and I will post it. Thanks!

**Comment by thorrak** [comment]
Fixed with the update I just pushed to dev

**Comment by anbayanyay** [comment]
I clicked the "Upgrade" link which had reappeared, and long story short my system's issue remains the same -- the word "Temperature" appears beside the place where the chart would normally be but no chart appears. I updated from the master branch and the chart was there, re-updated from dev and it's not. Is there something I need to do on my end to get it active? 

Please let me know if your troubleshooting efforts would benefit from me posting any logs, etc.

 Thanks!

**Comment by thorrak** [comment]
Doh. :(

Can you try two things—

First, click the gear icon in the upper right, choose “Update from GitHub”, make sure you’re on the dev branch and re-update? I was having issues with GitHub yesterday so it’s possible that things just didn’t update correctly. 

Assuming that didn’t work, can you log into the Django Admin (from the “gear” icon in the upper right), choose “Beers” (or Beer Logs, don’t remember off the top of my head), click into the beer you’re having issues with, and tell me what the version number listed is? It’s either going to be “1” or “2”. 

Am I correct to assume you don’t have a gravity sensor in this configuration attached to the temperature sensor?

**Comment by anbayanyay** [comment]
Hi, I am running the dev branch when the chart doesn't work. If I use the
upgrade3 script to fetch the master branch, the chart actually does show up.

As for the log model version, it's set to 1. (I tried setting it to 2 but
that didn't help the chart any, so I set it back to 1.)

I actually do have a Tilt hydrometer bound with the Arduino. Maybe I should
mention that if I go into the hydrometer dashboard instead of the Arduino
dashboard, the Tilt gravity / temperature chart there does show up
correctly. Hope that helps.

**Comment by guiwood** [comment]
Same problem here. Graph not showing after last update. I dont have a ispindel installed.

**Comment by thorrak** [comment]
I just pushed an update that should fix this. Let me know if you still have issues after updating!

**Comment by guiwood** [comment]
Just did it! Looks like now I can see the chart if I start a new beer. However, if I load a past beer log I can't see the chart.

**Comment by thorrak** [comment]
I got back home yesterday and was able to test using my "production" setup rather than the development one I have on my laptop and see the bug. I just pushed a fix to the "graphfix" branch which I will test tonight. Assuming it works, we'll get it merged & be done with this one.

Sorry for the false starts - the data file I had on my laptop apparently was something between v1 and v2 of the beer log!

**Comment by thorrak** [comment]
I just pulled the fix into the "dev" branch - Should work now. Let me know if there are any further issues!

**Comment by guiwood** [comment]
It is working again now! Thank you and keep up the good work! The software is awesome.
