### ISSUE TITLE
rounding issue

### ISSUE THREAD

**Issue by JonHeron** [thorrak/fermentrack#406]
Raspbian Stretch 9 on rp i3a
I am using fuscus as the controller and it appears there is a rounding error somewhere as the temperature readings have too many decimal points showing.
Perhaps this is fuscus related?
![Screenshot from 2019-12-23 11-45-52](https://user-images.githubusercontent.com/9784350/71369781-cedbc000-2579-11ea-99c2-5c5a66d90fa7.png)
With a hint in which script to look into this I can likely fix it myself.
Cheers,
Jon

**Comment by lbussy** [comment]
There's a couple of places you might look.  [This](https://github.com/thorrak/fermentrack/blob/0dfefbe9542a999c10a9c2085c9dcbbaa3ae12f8/brewpi-script/brewpi.py#L462-L466) is where the script sends the text to the web page.  [This](https://github.com/thorrak/fermentrack/blob/0dfefbe9542a999c10a9c2085c9dcbbaa3ae12f8/brewpi-script/brewpi.py#L737-L757) is where the information is received.  Either of these would be a reasonable place to round(temp, 2) the temperatures,

The author of Fuscus also seems to be active in other projects.  You might ask him via [an issue](https://github.com/andrewerrington/fuscus/issues) where you could do the same within his scripts.

**Comment by JonHeron** [comment]
Thanks I will look into that.
Cheers,
Jon

**Comment by thorrak** [comment]
@JonHeron The line you want to edit to fix this is here:
https://github.com/thorrak/fermentrack/blob/0dfefbe9542a999c10a9c2085c9dcbbaa3ae12f8/app/api/lcd.py#L36

The fix would probably be to change that line to something like 
`return "{:.1f}&deg; {}".format(temp, temp_format)` 

I'm not able to test that fix at the moment, but I can get this added to dev next time I pull code in

**Comment by JonHeron** [comment]
That was indeed the fix!
Thank you all for your efforts!
Merry Christmas!
Jon
![Screenshot from 2019-12-24 18-18-03](https://user-images.githubusercontent.com/9784350/71426578-c2d72780-2679-11ea-8e14-6d90e3058987.png)

**Comment by thorrak** [comment]
Reopening, as I need to get the fix merged in :)

**Comment by JonHeron** [comment]
I just fired this up again and see that while the mail panels are rounded to one decimal the float issue is still present in the right hand panel. This is after updating to the latest commit.
Cheers,
Jon
![Screenshot from 2020-02-01 19-31-29](https://user-images.githubusercontent.com/9784350/73601142-0b5feb80-452a-11ea-9b7b-71027114b567.png)

**Comment by JonHeron** [comment]
It appears this is still present in the right hand panels with the latest commit when using Fuscus as the controller.
![Screenshot from 2020-02-21 09-38-20](https://user-images.githubusercontent.com/9784350/75067762-c2151300-54bb-11ea-9321-6e11782a93db.png)

Cheers,
Jon
